FROM ubuntu:18.04

CMD while true; do sleep 2 ; echo "{\"app\": 0.2, \"foo\": \"bar\"}"; echo "{\"keydiff\": \"dummy\", \"fooss\": \"bar\"}"; echo " INFO: {\"app\": \"dummy\", \"foo\": \"bar\"}"; echo "Info: Unstructured log"; done
